#%RAML 0.8
title: VerbShaker API
baseUri: /
mediaType: application/json
protocols:
  - HTTP
version: 2.0
schemas:
  - Status: !include models/status.json
  - Config: !include models/config.json
  - Proverb: !include models/proverb.json
  - Proverbs: !include models/proverbs.json
  - Languages: !include models/languages.json
/status:
  displayName: Status
  description: Delivers Status-Information for verbshaker
  get:
    responses:
      200:
        body:
          application/json:
            schema: Status
            example: |
              {
              "status":"running"
              }
/config:
  displayName: Config
  description: Delivers Config-Information for verbshaker
  get:
    responses:
      200:
        body:
          application/json:
            schema: Config
            example: |
              {
                "port":8080,
                "proverbs":"proverbs/",
                "show_docs":false,
                "default": {
                  "backgroundcolor": "#000000",
                  "fontcolor": "#FFFFFF",
                  "fontsize": 12,
                  "fontfamily": "Neue Helvetica",
                  "hiddenNav": false,
                  "proverbbutton": true,
                  "autoupdate": 0,
                  "shareButton": true,
                  "unhideNavButton": true,
                  "introjs": true
                },
                "changeable": {
                  "language": true,
                  "backgroundcolor": true,
                  "fontcolor": true,
                  "fontsize": true,
                  "fontfamily": true,
                  "hideNav": true,
                  "proverbbutton": true,
                  "autoupdate": true
                }
              }
/api:
  displayName: Main API Endpoint
  description: Here we go
  /languages:
    displayName: Languages
    description: return Array of avaiable Languages
    get:
      responses:
        200:
          body:
            application/json:
              schema: Languages
              example: |
                [ "de", "en"]
  /random:
    displayName: Return a random Proverb from any language
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  front:"Morgenstund",
                  back:"fängt den Wurm",
                  combined:"Morgenstund fängt den Wurm",
                  language:"de"
                }
              schema: Proverb
  /{language}:
    displayName: Return all Proverbs for language
    uriParameters:
      language:
        example: de
        displayName: Language Code
        type: string
    get:
      responses:
        200:
          body:
            application/json:
              schema: Proverbs
              example: |
                [
                  ["Der frühe Vogel", "fängt den Wurm"],
                  ["Morgenstund", "hat Gold im Mund"]
                ]
    /random:
      displayName: Return a random proverb for the language
      get:
        responses:
          200:
            body:
              application/json:
                schema: Proverb
                example: |
                  {
                    front:"Morgenstund",
                    back:"fängt den Wurm",
                    combined:"Morgenstund fängt den Wurm",
                    language:"de"
                  }
